/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FormButton {
        "type": string;
    }
    interface FormInput {
        "label": string;
        "name": string;
        "required": boolean;
        "type": string;
        "value": string;
        "vspace": boolean;
    }
    interface LoginForm {
    }
}
declare global {
    interface HTMLFormButtonElement extends Components.FormButton, HTMLStencilElement {
    }
    var HTMLFormButtonElement: {
        prototype: HTMLFormButtonElement;
        new (): HTMLFormButtonElement;
    };
    interface HTMLFormInputElement extends Components.FormInput, HTMLStencilElement {
    }
    var HTMLFormInputElement: {
        prototype: HTMLFormInputElement;
        new (): HTMLFormInputElement;
    };
    interface HTMLLoginFormElement extends Components.LoginForm, HTMLStencilElement {
    }
    var HTMLLoginFormElement: {
        prototype: HTMLLoginFormElement;
        new (): HTMLLoginFormElement;
    };
    interface HTMLElementTagNameMap {
        "form-button": HTMLFormButtonElement;
        "form-input": HTMLFormInputElement;
        "login-form": HTMLLoginFormElement;
    }
}
declare namespace LocalJSX {
    interface FormButton {
        "type"?: string;
    }
    interface FormInput {
        "label": string;
        "name": string;
        "required"?: boolean;
        "type"?: string;
        "value"?: string;
        "vspace"?: boolean;
    }
    interface LoginForm {
    }
    interface IntrinsicElements {
        "form-button": FormButton;
        "form-input": FormInput;
        "login-form": LoginForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "form-button": LocalJSX.FormButton & JSXBase.HTMLAttributes<HTMLFormButtonElement>;
            "form-input": LocalJSX.FormInput & JSXBase.HTMLAttributes<HTMLFormInputElement>;
            "login-form": LocalJSX.LoginForm & JSXBase.HTMLAttributes<HTMLLoginFormElement>;
        }
    }
}
